{{- if .Values.jupyterNotebook.enabled -}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: juputer-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.jupyterNotebook.serviceAccount }}
roleRef:
  kind: Role
  name: juputer-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
