dependencies:
  - name: nuclio
    version: "0.18.3"
    repository: "https://nuclio.github.io/nuclio/charts"
  - name: mlrun
    version: "0.9.16"
    repository: "https://v3io.github.io/helm-charts/stable"
    condition: mlrun.enabled
  - name: mpi-operator
    version: "0.6.0"
    repository: "https://v3io.github.io/helm-charts/stable"
  - name: minio
    repository: "https://charts.min.io/"
    version: "4.0.2"
    condition: minio.enabled
  - name: spark-operator
    repository: "https://googlecloudplatform.github.io/spark-on-k8s-operator"
    version: "1.1.25"
    condition: spark-operator.enabled
  - name: grafana
    repository: "https://grafana.github.io/helm-charts"
    version: "7.3.3"
    condition: grafana.enabled
  - name: prometheus
    repository: "https://prometheus-community.github.io/helm-charts"
    version: "25.16.0"
    condition: prometheus.enabled